spring:
  application:
    name: lecture

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.126.4:3306/test
    username: root
    password: root

  redis:
    host: 112.74.126.4
    port: 6379
    lettuce:
      pool:
        max-active: 4
        max-wait: -1
        max-idle: 4
        min-idle: 0

#Redis自定义缓存时间配置，单位为秒
caching:
  ttl-map:
    skuInfo: 10

mybatis:
  mapper-locations: classpath*:/mybatis/*.xml
  type-aliases-package: com.lecture.domain.entities
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath*:/mybatis/*.xml
  type-aliases-package: com.lecture.domain.entities
#  config-location:
server:
  error:
    include-exception: false
    include-message: always
  tomcat:
    max-connections: 5000
    accept-count: 50
    threads:
      max: 300
      min-spare: 40



